export const l = (...a) => console.log(...a);
export const e = (...a) => console.error(...a);
export const w = (...a) => console.warn(...a);
export const i = (...a) => console.info(...a);
export const d = (...a) => console.debug(...a);
export const t = (...a) => console.trace(...a);
export const cl = () => console.clear();
export const lg = l;
export const er = e;
export const wn = w;
export const inf = i;
export const db = d;
export const tr = t;
